"""Create WordOfTheDay table

Revision ID: 0554fc46a9ce
Revises: 48a57012c95e
Create Date: 2024-12-04 11:38:52.368927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0554fc46a9ce'
down_revision = '48a57012c95e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('words_entered_today',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('words_entered_today',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
