"""Create Word table

Revision ID: 3f6c8d5bb8f5
Revises: 0554fc46a9ce
Create Date: 2024-12-09 19:44:14.705155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6c8d5bb8f5'
down_revision = '0554fc46a9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('word', sa.String(length=150), nullable=False),
        sa.Column('date_added', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
