"""Add achievements to User model

Revision ID: 73985a9bd4fb
Revises: ebbdf4509b8b
Create Date: 2024-12-01 12:55:05.197398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73985a9bd4fb'
down_revision = 'ebbdf4509b8b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievements', sa.Text(), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('achievements')

    # ### end Alembic commands ###
