"""Add is_private to User model

Revision ID: 88755b08ed4e
Revises: 253f2915da9f
Create Date: 2025-01-10 11:37:15.689356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88755b08ed4e'
down_revision = '253f2915da9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
