"""Add definition to WordOfTheDay

Revision ID: ce3c6c017cb4
Revises: b5c316c0ea10
Create Date: 2025-01-11 23:41:54.545959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3c6c017cb4'
down_revision = 'b5c316c0ea10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_of_the_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_of_the_day', schema=None) as batch_op:
        batch_op.drop_column('definition')

    # ### end Alembic commands ###
